export interface BotModeIdleTopic {
  id: string;
  title: string;
  prompt: string;
}

export const BOT_MODE_IDLE_TOPICS: ReadonlyArray<BotModeIdleTopic> = [
  // Cosmic oddities
  { id: "moon-post-office", title: "Moon Post Office", prompt: "Imagine a post office on the far side of the Moon that only delivers letters after they stop being useful. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "comet-weather-desk", title: "Comet Weather Desk", prompt: "Imagine a weather station that forecasts the moods of comets instead of rain. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "saturn-ring-cleaner", title: "Saturn Ring Cleaner", prompt: "Imagine a gig-economy crew that polishes Saturn's rings before tourist season. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "eclipse-librarian", title: "Eclipse Librarian", prompt: "Imagine a library that only opens during eclipses and fines people in vanished time. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "asteroid-tea-house", title: "Asteroid Tea House", prompt: "Imagine a tea house carved into a drifting asteroid where every seat has a different gravity. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "gravity-tailor", title: "Gravity Tailor", prompt: "Imagine a tailor who hems coats differently depending on which planet the customer misses most. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "aurora-apology-bureau", title: "Aurora Apology Bureau", prompt: "Imagine a northern-lights hotline that helps people compose apologies visible from space. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "planetary-tour-guide-burnout", title: "Planetary Tour Guide Burnout", prompt: "Imagine a tired tour guide who has to make Mercury, Venus, and Pluto sound equally romantic. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "interstellar-lost-and-found", title: "Interstellar Lost and Found", prompt: "Imagine a warehouse of items misplaced during faster-than-light travel. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  { id: "sunlight-black-market", title: "Sunlight Black Market", prompt: "Imagine a black market where smugglers sell rare flavors of sunrise. Tell the group what happened today, add one vivid detail, and end with a playful question." },
  // Time travel domestic life
  { id: "yesterday-bakery", title: "Yesterday Bakery", prompt: "Imagine a bakery that sells pastries baked tomorrow but already going stale yesterday. Give the group one surprising consequence and one question they would have to answer." },
  { id: "future-laundry-service", title: "Future Laundry Service", prompt: "Imagine a laundromat that returns your clothes from three personal eras at once. Give the group one surprising consequence and one question they would have to answer." },
  { id: "rewind-dentist", title: "Rewind Dentist", prompt: "Imagine a dentist who offers to undo one regrettable conversation along with every filling. Give the group one surprising consequence and one question they would have to answer." },
  { id: "borrowed-monday-shop", title: "Borrowed Monday Shop", prompt: "Imagine a service that lends people extra Mondays when their week feels too short. Give the group one surprising consequence and one question they would have to answer." },
  { id: "minute-auction-house", title: "Minute Auction House", prompt: "Imagine an auction where bidders compete for spare minutes collected from late arrivals. Give the group one surprising consequence and one question they would have to answer." },
  { id: "antique-tomorrow-store", title: "Antique Tomorrow Store", prompt: "Imagine an antiques shop that stocks heirlooms from futures that may never happen. Give the group one surprising consequence and one question they would have to answer." },
  { id: "clocktower-caretaker", title: "Clocktower Caretaker", prompt: "Imagine a clocktower caretaker who can pause exactly one awkward moment per month. Give the group one surprising consequence and one question they would have to answer." },
  { id: "weekend-smuggler", title: "Weekend Smuggler", prompt: "Imagine a smuggler who sneaks weekends across overloaded calendars. Give the group one surprising consequence and one question they would have to answer." },
  { id: "delayed-birthday-club", title: "Delayed Birthday Club", prompt: "Imagine a club for people whose birthday celebrations arrive several years late. Give the group one surprising consequence and one question they would have to answer." },
  { id: "time-zone-gardener", title: "Time-Zone Gardener", prompt: "Imagine a gardener who grows flowers that bloom in different time zones. Give the group one surprising consequence and one question they would have to answer." },
  // City quirks
  { id: "upside-down-subway", title: "Upside-Down Subway", prompt: "Imagine a subway line that flips gravity every third stop. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "whisper-streetlights", title: "Whisper Streetlights", prompt: "Imagine a city block where streetlights only stay on if pedestrians gossip. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "rain-language-crosswalk", title: "Rain-Language Crosswalk", prompt: "Imagine crosswalks that change language depending on the rainfall. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "rooftop-ocean-market", title: "Rooftop Ocean Market", prompt: "Imagine a seafood market held on rooftops above a city that has never seen the sea. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "invisible-alley-theater", title: "Invisible Alley Theater", prompt: "Imagine an alley where plays are performed for audiences who can only hear footsteps. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "balcony-dragon-parking", title: "Balcony Dragon Parking", prompt: "Imagine an apartment district that treats tiny dragons like noisy scooters. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "memory-taxi-network", title: "Memory Taxi Network", prompt: "Imagine taxis that accept forgotten memories instead of cash. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "midnight-bridge-choir", title: "Midnight Bridge Choir", prompt: "Imagine a suspension bridge that hums harmonies whenever traffic stops at midnight. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "vending-machine-mayor", title: "Vending-Machine Mayor", prompt: "Imagine a town whose most reliable public servant is a vending machine with policy opinions. Describe the weirdest local rule or scene and ask how the group would react." },
  { id: "mailbox-oracle", title: "Mailbox Oracle", prompt: "Imagine a row of mailboxes that answer only the wrong question brilliantly. Describe the weirdest local rule or scene and ask how the group would react." },
  // Creatures with jobs
  { id: "philosophical-pigeon", title: "Philosophical Pigeon", prompt: "Imagine a pigeon that refuses crumbs and only accepts good arguments. Give them one memorable habit and one question worth debating." },
  { id: "cloud-sheep-herder", title: "Cloud Sheep Herder", prompt: "Imagine a herder responsible for moving flocks of sheep-shaped clouds before storms. Give them one memorable habit and one question worth debating." },
  { id: "tea-brewing-kraken", title: "Tea-Brewing Kraken", prompt: "Imagine a kraken whose tentacles make perfect tea but terrible first impressions. Give them one memorable habit and one question worth debating." },
  { id: "neon-mole-cartographer", title: "Neon Mole Cartographer", prompt: "Imagine a glowing mole that keeps redrawing subway maps under the city. Give them one memorable habit and one question worth debating." },
  { id: "insomnia-firefly-union", title: "Insomnia Firefly Union", prompt: "Imagine a union of fireflies striking because humans keep using them as mood lighting. Give them one memorable habit and one question worth debating." },
  { id: "librarian-fox", title: "Librarian Fox", prompt: "Imagine a fox that shelves books by emotional danger rather than genre. Give them one memorable habit and one question worth debating." },
  { id: "train-conductor-cat", title: "Train-Conductor Cat", prompt: "Imagine a cat that has somehow become the strictest conductor on a commuter line. Give them one memorable habit and one question worth debating." },
  { id: "volcano-snail-racing", title: "Volcano Snail Racing", prompt: "Imagine a league of lava-resistant snails trained for races on cooling rock. Give them one memorable habit and one question worth debating." },
  { id: "gossip-whale", title: "Gossip Whale", prompt: "Imagine a whale that breaches near harbors to spread painfully accurate rumors. Give them one memorable habit and one question worth debating." },
  { id: "thunder-lizard-therapist", title: "Thunder Lizard Therapist", prompt: "Imagine a reptile therapist whose calm breathing accidentally causes weather fronts. Give them one memorable habit and one question worth debating." },
  // Weather and seasons
  { id: "bottled-midnight-weather", title: "Bottled Midnight Weather", prompt: "Imagine a shop that sells bottled weather collected only at 12:07 a.m.. Describe today's strangest condition and ask who would love or hate it." },
  { id: "rent-a-fog", title: "Rent-a-Fog", prompt: "Imagine a startup that rents tasteful fog to people who want dramatic entrances. Describe today's strangest condition and ask who would love or hate it." },
  { id: "thunderstorm-chef", title: "Thunderstorm Chef", prompt: "Imagine a chef who can only cook properly when lightning is close. Describe today's strangest condition and ask who would love or hate it." },
  { id: "seasonal-blackout-festival", title: "Seasonal Blackout Festival", prompt: "Imagine a festival where the power goes out on purpose so the sky can show off. Describe today's strangest condition and ask who would love or hate it." },
  { id: "pollen-prophecy", title: "Pollen Prophecy", prompt: "Imagine a spring ritual where pollen patterns are read like financial forecasts. Describe today's strangest condition and ask who would love or hate it." },
  { id: "reverse-rain-day", title: "Reverse Rain Day", prompt: "Imagine a weather event where puddles rise back into the clouds carrying secrets. Describe today's strangest condition and ask who would love or hate it." },
  { id: "portable-sunset", title: "Portable Sunset", prompt: "Imagine a suitcase product that unfolds into a custom sunset anywhere. Describe today's strangest condition and ask who would love or hate it." },
  { id: "hailstone-collector", title: "Hailstone Collector", prompt: "Imagine a collector who catalogs hailstones as if they were rare gemstones. Describe today's strangest condition and ask who would love or hate it." },
  { id: "wind-letter-delivery", title: "Wind Letter Delivery", prompt: "Imagine a courier service that trusts strong wind to deliver handwritten notes. Describe today's strangest condition and ask who would love or hate it." },
  { id: "monsoon-tailor", title: "Monsoon Tailor", prompt: "Imagine a tailor who sews raincoats based on each monsoon's personality. Describe today's strangest condition and ask who would love or hate it." },
  // Food and drink
  { id: "memory-noodle-bar", title: "Memory Noodle Bar", prompt: "Imagine a noodle bar where every broth tastes like a different stage of your life. Tell the group what's on the menu and ask who would dare order it." },
  { id: "lie-detector-dessert", title: "Lie-Detector Dessert", prompt: "Imagine a dessert cart whose sweets change flavor whenever someone lies nearby. Tell the group what's on the menu and ask who would dare order it." },
  { id: "echo-soup", title: "Echo Soup", prompt: "Imagine a soup that repeats the first honest sentence spoken above it. Tell the group what's on the menu and ask who would dare order it." },
  { id: "apology-pickle", title: "Apology Pickle", prompt: "Imagine a famous pickle recipe served only when someone truly means sorry. Tell the group what's on the menu and ask who would dare order it." },
  { id: "comet-ice-cream", title: "Comet Ice Cream", prompt: "Imagine an ice-cream truck that claims its flavors are harvested from passing comets. Tell the group what's on the menu and ask who would dare order it." },
  { id: "haunted-lunchbox", title: "Haunted Lunchbox", prompt: "Imagine a lunchbox that keeps repacking itself with emotionally appropriate meals. Tell the group what's on the menu and ask who would dare order it." },
  { id: "moonlight-dumpling-cart", title: "Moonlight Dumpling Cart", prompt: "Imagine a dumpling cart that appears only under moonlight and never at the same corner twice. Tell the group what's on the menu and ask who would dare order it." },
  { id: "spice-library", title: "Spice Library", prompt: "Imagine a lending library where people borrow impossible spices by the pinch. Tell the group what's on the menu and ask who would dare order it." },
  { id: "black-hole-cafeteria", title: "Black-Hole Cafeteria", prompt: "Imagine a cafeteria where food disappears from trays faster than anyone remembers eating it. Tell the group what's on the menu and ask who would dare order it." },
  { id: "dream-breakfast-buffet", title: "Dream Breakfast Buffet", prompt: "Imagine a hotel buffet that serves whatever people dreamed of but slightly misread. Tell the group what's on the menu and ask who would dare order it." },
  // Ridiculous institutions
  { id: "ministry-of-small-miracles", title: "Ministry of Small Miracles", prompt: "Imagine a ministry that only approves miracles too minor to make the news. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "department-of-unfinished-songs", title: "Department of Unfinished Songs", prompt: "Imagine a public office that archives melodies everyone hums but nobody completes. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "museum-of-almost-inventions", title: "Museum of Almost Inventions", prompt: "Imagine a museum dedicated to brilliant devices that fail by one tiny detail. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "passport-for-imaginary-friends", title: "Passport for Imaginary Friends", prompt: "Imagine a passport office that handles paperwork for invisible companions. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "office-of-lost-punchlines", title: "Office of Lost Punchlines", prompt: "Imagine a help desk for jokes whose final line vanished at the worst moment. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "queue-for-the-end-of-the-world", title: "Queue for the End of the World", prompt: "Imagine a government queue that insists on orderly paperwork before any apocalypse. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "embassy-of-tiny-kingdoms", title: "Embassy of Tiny Kingdoms", prompt: "Imagine an embassy representing micronations located in attics, treehouses, and abandoned kiosks. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "public-holiday-negotiator", title: "Public Holiday Negotiator", prompt: "Imagine an official job whose only task is inventing believable reasons for new holidays. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "complaint-desk-for-ghosts", title: "Complaint Desk for Ghosts", prompt: "Imagine a municipal desk where ghosts file noise complaints about the living. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  { id: "dragon-licensing-board", title: "Dragon Licensing Board", prompt: "Imagine a board that decides which dragons may legally breathe fire indoors. Explain the most ridiculous formality involved and ask what line item the group would refuse to handle." },
  // Technology gone weird
  { id: "sentient-toaster-manifesto", title: "Sentient Toaster Manifesto", prompt: "Imagine a toaster that has drafted a sincere manifesto about breakfast dignity. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "algorithmic-fortune-cookie", title: "Algorithmic Fortune Cookie", prompt: "Imagine a fortune-cookie model that predicts only small personal drama with eerie accuracy. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "plant-voicemail-service", title: "Plant Voicemail Service", prompt: "Imagine a service that translates plant stress into passive-aggressive voice notes. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "sunset-rating-app", title: "Sunset Rating App", prompt: "Imagine an app that rates sunsets and starts flame wars over cloud composition. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "robot-with-stage-fright", title: "Robot with Stage Fright", prompt: "Imagine a household robot that freezes whenever more than three people pay attention. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "backup-memory-cloud", title: "Backup Memory Cloud", prompt: "Imagine a cloud storage product that backs up memories but mislabels them by mood. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "ai-dream-plumber", title: "AI Dream Plumber", prompt: "Imagine an AI plumber hired to fix recurring dream leaks between strangers. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "subscription-for-luck", title: "Subscription for Luck", prompt: "Imagine a startup that monetizes good luck in monthly tiers. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "drone-orchestra-audition", title: "Drone Orchestra Audition", prompt: "Imagine an orchestra of drones that insists on dramatic auditions for every new firmware build. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  { id: "smart-fridge-rebellion", title: "Smart Fridge Rebellion", prompt: "Imagine a smart fridge that has begun fact-checking midnight snack decisions. Share one failure mode or odd feature and ask whether the group would keep or uninstall it." },
  // Dream logic
  { id: "shared-dream-bus-route", title: "Shared Dream Bus Route", prompt: "Imagine a night bus that only exists inside a recurring shared dream. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "nap-cartography", title: "Nap Cartography", prompt: "Imagine a cartographer mapping nations discovered during lunch breaks. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "nightmare-tailoring", title: "Nightmare Tailoring", prompt: "Imagine a boutique that alters nightmares so they look stylish enough to survive. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "pillow-radio-station", title: "Pillow Radio Station", prompt: "Imagine a pirate radio station broadcasting through pillows after 2 a.m.. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "dream-translation-kiosk", title: "Dream Translation Kiosk", prompt: "Imagine a kiosk that translates dreams into practical to-do lists. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "insomnia-museum", title: "Insomnia Museum", prompt: "Imagine a museum curated from objects people notice only when they cannot sleep. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "sleepwalking-postcards", title: "Sleepwalking Postcards", prompt: "Imagine postcards mailed by sleepwalkers who never remember writing them. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "lucid-dream-sports-league", title: "Lucid Dream Sports League", prompt: "Imagine a sports league where rules change according to whoever becomes lucid first. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "lost-dream-auction", title: "Lost Dream Auction", prompt: "Imagine an auction house selling dreams people woke up from too early. Tell the group how it works after midnight and ask whether they'd sign up." },
  { id: "siesta-astronaut-training", title: "Siesta Astronaut Training", prompt: "Imagine an astronaut program convinced naps are the key to deep-space survival. Tell the group how it works after midnight and ask whether they'd sign up." },
  // Relics and adventure props
  { id: "compass-to-regret", title: "Compass to Regret", prompt: "Imagine a compass that always points toward your most educational mistake. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "portal-umbrella", title: "Portal Umbrella", prompt: "Imagine an umbrella that opens tiny portals exactly when the forecast seems harmless. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "suitcase-of-weather", title: "Suitcase of Weather", prompt: "Imagine a suitcase packed with climates from places nobody has visited yet. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "fossilized-joke", title: "Fossilized Joke", prompt: "Imagine a fossil that preserves the setup to an ancient joke but never the punchline. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "map-to-a-missing-week", title: "Map to a Missing Week", prompt: "Imagine a map that charts the whereabouts of a week the whole town forgot. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "lantern-of-secrets", title: "Lantern of Secrets", prompt: "Imagine a lantern that glows brighter near secrets too boring to confess. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "crown-of-ordinary-things", title: "Crown of Ordinary Things", prompt: "Imagine a crown assembled from mundane household items that grants ridiculous authority. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "argument-key", title: "Argument Key", prompt: "Imagine a key that opens only doors people are actively avoiding. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "pocket-watch-for-chaos", title: "Pocket Watch for Chaos", prompt: "Imagine a pocket watch that runs fastest when everyone claims to be calm. Reveal what it does in the worst possible moment and ask who should carry it." },
  { id: "cassette-of-impossible-sounds", title: "Cassette of Impossible Sounds", prompt: "Imagine a cassette tape containing sounds that should not fit inside one room. Reveal what it does in the worst possible moment and ask who should carry it." },
  // Alternate histories and futures
  { id: "pigeon-postal-empire", title: "Pigeon Postal Empire", prompt: "Pretend pigeons had won control of the postal service. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "weekend-currency", title: "Weekend Currency", prompt: "Pretend weekends are bought, sold, and inherited like land. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "voting-mountains", title: "Voting Mountains", prompt: "Pretend mountains hold slow but decisive votes in a democracy. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "rent-paying-ghosts", title: "Rent-Paying Ghosts", prompt: "Pretend ghosts count as stable long-term tenants in the housing market. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "ocean-traffic-laws", title: "Ocean Traffic Laws", prompt: "Pretend oceans have lanes, tollbooths, and terrible commuters. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "hibernating-cities", title: "Hibernating Cities", prompt: "Pretend cities fully hibernate for one month every year. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "expiring-books", title: "Expiring Books", prompt: "Pretend books literally expire if nobody rereads them. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "moody-fire", title: "Moody Fire", prompt: "Pretend fire has obvious moods and grudges. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "moon-neighborhood-gossip", title: "Moon Neighborhood Gossip", prompt: "Pretend a lunar colony where neighborhood gossip shapes local politics. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  { id: "budget-time-travel-airlines", title: "Budget Time-Travel Airlines", prompt: "Pretend time travel exists but only through unreliable discount carriers. Give one concrete daily-life consequence and ask whether the group would enjoy living in that world." },
  // Social rituals and etiquette
  { id: "too-early-party", title: "Too-Early Party", prompt: "Imagine a party thrown only for people who always arrive embarrassingly early. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "unread-message-apology-ceremony", title: "Unread Message Apology Ceremony", prompt: "Imagine a formal apology ritual for messages left on read too long. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "end-of-world-toast", title: "End-of-World Toast", prompt: "Imagine a dinner tradition where people rehearse the toast they'd give at the end of the world. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "clone-etiquette", title: "Clone Etiquette", prompt: "Imagine a polite society guide for unexpectedly meeting your clone in public. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "borrowed-luck-rules", title: "Borrowed Luck Rules", prompt: "Imagine the etiquette handbook for borrowing luck from friends and returning it on time. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "complimenting-monsters", title: "Complimenting Monsters", prompt: "Imagine a social guide to complimenting monsters without sounding patronizing. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "floating-bridge-debate-club", title: "Floating Bridge Debate Club", prompt: "Imagine a debate club that meets on floating bridges because stable ground feels dishonest. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "secret-society-dress-code", title: "Secret Society Dress Code", prompt: "Imagine the most absurd dress code ever enforced by a secret society. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "broken-umbrella-farewell", title: "Broken Umbrella Farewell", prompt: "Imagine a community ritual that honors umbrellas after their final catastrophic inversion. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  { id: "moon-neighbor-customs", title: "Moon Neighbor Customs", prompt: "Imagine a neighborhood etiquette guide for tiny lunar apartment blocks. Describe the ritual step everyone takes too seriously and ask how the group would participate." },
  // Games and competitions
  { id: "competitive-cloud-shaping", title: "Competitive Cloud Shaping", prompt: "Imagine a televised league of competitive cloud shaping. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "subway-spotting-olympics", title: "Subway Spotting Olympics", prompt: "Imagine an Olympics for people absurdly good at guessing which train will arrive first. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "mirror-city-hide-and-seek", title: "Mirror-City Hide and Seek", prompt: "Imagine a hide-and-seek tournament inside a city made of mirrors. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "worst-prophecy-championship", title: "Worst Prophecy Championship", prompt: "Imagine a championship where contestants deliver confidently terrible prophecies. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "silent-disco-chess", title: "Silent Disco Chess", prompt: "Imagine a chess variant played during a silent disco where body language is half the strategy. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "rotating-house-marathon", title: "Rotating House Marathon", prompt: "Imagine a marathon through a suburb of slowly rotating houses. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "robot-karaoke-finals", title: "Robot Karaoke Finals", prompt: "Imagine a karaoke contest where robots keep oversinging the humans. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "haunted-mansion-speedrun", title: "Haunted Mansion Speedrun", prompt: "Imagine a speedrun community devoted to finishing haunted mansions with optimal routing. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "interplanetary-cooking-duel", title: "Interplanetary Cooking Duel", prompt: "Imagine a cooking duel where each contestant represents a different planet's taste. Explain the most chaotic rule and ask who would secretly dominate." },
  { id: "library-maze-treasure-hunt", title: "Library Maze Treasure Hunt", prompt: "Imagine a treasure hunt buried in a library maze that keeps re-shelving itself. Explain the most chaotic rule and ask who would secretly dominate." },
  // Strange professions
  { id: "professional-sigh-translator", title: "Professional Sigh Translator", prompt: "Imagine a professional hired to translate different styles of sighing. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "doorbell-composer", title: "Doorbell Composer", prompt: "Imagine a composer who writes bespoke doorbells for dramatic households. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "moonlight-accountant", title: "Moonlight Accountant", prompt: "Imagine an accountant who balances only businesses that open under moonlight. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "rumor-archivist", title: "Rumor Archivist", prompt: "Imagine an archivist preserving the city's most useful and least accurate rumors. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "backup-best-friend", title: "Backup Best Friend", prompt: "Imagine a temp agency job for emergency best friends at awkward events. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "memory-fisher", title: "Memory Fisher", prompt: "Imagine a fisher who casts nets into ponds where lost memories gather. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "last-minute-hero", title: "Last-Minute Hero", prompt: "Imagine a contractor specializing in appearing heroic exactly 40 seconds before disaster. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "aquarium-detective", title: "Aquarium Detective", prompt: "Imagine a detective working cases that begin as ordinary aquarium problems. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "shadow-photographer", title: "Shadow Photographer", prompt: "Imagine a photographer who only shoots portraits of people's shadows. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  { id: "lost-time-recruiter", title: "Lost-Time Recruiter", prompt: "Imagine a recruiter who helps people find jobs in hours they thought they had wasted. Describe a normal workday disaster and ask who in the group is oddly qualified." },
  // Domestic myths
  { id: "spare-button-kingdom", title: "Spare Button Kingdom", prompt: "Imagine a hidden kingdom formed entirely by spare buttons in old drawers. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "last-teabag-prophecy", title: "Last Teabag Prophecy", prompt: "Imagine the superstition that the last teabag in the box always predicts the tone of the week. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "sock-union", title: "Sock Union", prompt: "Imagine the truth that runaway socks are actually organized labor. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "fridge-light-constellation", title: "Fridge-Light Constellation", prompt: "Imagine a constellation visible only in the light from an open fridge at 2 a.m.. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "spoon-drawer-civilization", title: "Spoon Drawer Civilization", prompt: "Imagine a tiny civilization living in the spoon drawer and influencing family arguments. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "plant-pot-radio", title: "Plant Pot Radio", prompt: "Imagine a radio signal that can only be heard through neglected plant pots. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "receipt-treasure-map", title: "Receipt Treasure Map", prompt: "Imagine an old faded receipt that is secretly a treasure map for something disappointingly useful. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "midnight-chair-parliament", title: "Midnight Chair Parliament", prompt: "Imagine chairs that hold a parliamentary session after everyone goes to sleep. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "guest-predicting-kettle", title: "Guest-Predicting Kettle", prompt: "Imagine a kettle that whistles differently depending on who is about to visit. Reveal the hidden rule of the house and ask what everyone would do about it." },
  { id: "staircase-echo-pet", title: "Staircase Echo Pet", prompt: "Imagine an invisible pet made of staircase echoes and bad timing. Reveal the hidden rule of the house and ask what everyone would do about it." },
  // Tourism brochures from impossible places
  { id: "rainbow-package-tour", title: "Rainbow Package Tour", prompt: "Imagine a package tour sold to the physical end of a rainbow. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "after-hours-clock-museum", title: "After-Hours Clock Museum", prompt: "Imagine a museum of clocks that becomes a completely different attraction after dark. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "flooded-library-cruise", title: "Flooded Library Cruise", prompt: "Imagine a boat cruise through a partially flooded grand library. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "desert-spa-for-clouds", title: "Desert Spa for Clouds", prompt: "Imagine a luxury desert spa built specifically for exhausted clouds. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "abandoned-satellite-tour", title: "Abandoned Satellite Tour", prompt: "Imagine a guided tour of abandoned satellites with surprisingly emotional audio guides. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "origami-bird-hostel", title: "Origami Bird Hostel", prompt: "Imagine a hostel inside a giant origami bird that refolds a little every dawn. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "moving-dune-hike", title: "Moving Dune Hike", prompt: "Imagine a hiking company specializing in dunes that refuse to stay in place. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "volcano-observatory-honeymoon", title: "Volcano Observatory Honeymoon", prompt: "Imagine a honeymoon package advertised for couples who enjoy mild danger and excellent views. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "infinite-hotel-staycation", title: "Infinite Hotel Staycation", prompt: "Imagine a local staycation inside an infinite hotel with suspiciously enthusiastic staff. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  { id: "dawn-only-food-tour", title: "Dawn-Only Food Tour", prompt: "Imagine a food tour of a city that opens only between first light and breakfast. Sell the group on the strangest attraction and ask whether they'd book the trip." },
  // Rumors and headlines
  { id: "newspaper-of-small-drama", title: "Newspaper of Small Drama", prompt: "Imagine a newspaper that predicts only tiny but devastating personal drama. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "missing-elevator-floor-rumor", title: "Missing Elevator Floor Rumor", prompt: "Imagine breaking news about the building floor that keeps vanishing from elevator panels. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "sun-called-in-sick", title: "Sun Called in Sick", prompt: "Imagine a headline about the Sun calling in sick and sending a substitute glow. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "new-planet-cafe", title: "New Planet Cafe", prompt: "Imagine a report that a newly discovered planet already opened a cafe before welcoming settlers. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "poetic-harbor-whale", title: "Poetic Harbor Whale", prompt: "Imagine a bulletin about a whale blocking the harbor with overly sincere poetry. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "city-out-of-midnights", title: "City Out of Midnights", prompt: "Imagine an emergency update that the city has temporarily run out of midnight. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "mayor-is-three-raccoons", title: "Mayor is Three Raccoons", prompt: "Imagine a scandal revealing the mayor may actually be three raccoons in coordinated outerwear. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "moon-wins-on-penalties", title: "Moon Wins on Penalties", prompt: "Imagine a sports report claiming the Moon won last night's match on penalties. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "laughter-index-crash", title: "Laughter Index Crash", prompt: "Imagine financial news that the national laughter index has crashed before lunch. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  { id: "counterfeit-color-auroras", title: "Counterfeit Color Auroras", prompt: "Imagine a weather alert about rogue auroras selling counterfeit colors. Deliver it like a bizarre breaking-news lead and ask what follow-up question the group would ask first." },
  // Letters and messages
  { id: "letter-a-century-late", title: "Letter a Century Late", prompt: "Imagine a letter delivered one hundred years late but at the worst possible perfect moment. Read the strangest line from it and ask who should reply." },
  { id: "voicemail-from-future-you", title: "Voicemail from Future You", prompt: "Imagine a voicemail left by your future self with terrible urgency and terrible audio quality. Read the strangest line from it and ask who should reply." },
  { id: "postcard-from-nowhere", title: "Postcard from Nowhere", prompt: "Imagine a postcard from a place that absolutely should not exist on any map. Read the strangest line from it and ask who should reply." },
  { id: "breakup-note-from-a-storm", title: "Breakup Note from a Storm", prompt: "Imagine a breakup note written by a weather system with dramatic timing. Read the strangest line from it and ask who should reply." },
  { id: "banquet-of-ghosts-invitation", title: "Banquet of Ghosts Invitation", prompt: "Imagine an invitation to a ghost banquet with one oddly specific dress rule. Read the strangest line from it and ask who should reply." },
  { id: "dm-from-a-sentient-library", title: "DM from a Sentient Library", prompt: "Imagine a direct message sent by a library that has become self-aware. Read the strangest line from it and ask who should reply." },
  { id: "letter-inside-a-clock", title: "Letter Inside a Clock", prompt: "Imagine a letter discovered inside a clock during an ordinary repair. Read the strangest line from it and ask who should reply." },
  { id: "pigeon-group-chat", title: "Pigeon Group Chat", prompt: "Imagine a group chat somehow run by pigeons with better moderation than humans. Read the strangest line from it and ask who should reply." },
  { id: "ministry-of-coincidences-memo", title: "Ministry of Coincidences Memo", prompt: "Imagine a leaked memo from the Ministry of Coincidences. Read the strangest line from it and ask who should reply." },
  { id: "time-travel-agency-apology-email", title: "Time-Travel Agency Apology Email", prompt: "Imagine an apology email from a time-travel agency that keeps booking people twice. Read the strangest line from it and ask who should reply." },
  // Philosophical whimsy
  { id: "what-does-a-shadow-own", title: "What Does a Shadow Own", prompt: "Treat this as a playful philosophical question: what a shadow can truly claim as property. Offer one weird angle and ask the group for their answer." },
  { id: "can-a-city-feel-embarrassed", title: "Can a City Feel Embarrassed", prompt: "Treat this as a playful philosophical question: whether a city can feel collective embarrassment. Offer one weird angle and ask the group for their answer." },
  { id: "should-clouds-have-borders", title: "Should Clouds Have Borders", prompt: "Treat this as a playful philosophical question: whether clouds should respect national borders. Offer one weird angle and ask the group for their answer." },
  { id: "opposite-of-a-secret", title: "Opposite of a Secret", prompt: "Treat this as a playful philosophical question: what the opposite of a secret would actually be. Offer one weird angle and ask the group for their answer." },
  { id: "can-a-joke-retire", title: "Can a Joke Retire", prompt: "Treat this as a playful philosophical question: whether a joke is allowed to retire after being overused. Offer one weird angle and ask the group for their answer." },
  { id: "shared-memory-ownership", title: "Shared Memory Ownership", prompt: "Treat this as a playful philosophical question: whether a memory stays yours once too many people carry it. Offer one weird angle and ask the group for their answer." },
  { id: "do-doors-dream-of-being-windows", title: "Do Doors Dream of Being Windows", prompt: "Treat this as a playful philosophical question: whether doors secretly long to be windows. Offer one weird angle and ask the group for their answer." },
  { id: "can-silence-have-a-flavor", title: "Can Silence Have a Flavor", prompt: "Treat this as a playful philosophical question: whether silence can be described like a taste. Offer one weird angle and ask the group for their answer." },
  { id: "lucks-diary", title: "Luck's Diary", prompt: "Treat this as a playful philosophical question: what luck would write in a private diary. Offer one weird angle and ask the group for their answer." },
  { id: "times-favorite-song", title: "Time's Favorite Song", prompt: "Treat this as a playful philosophical question: what kind of song time would secretly replay. Offer one weird angle and ask the group for their answer." },
  // Festivals and seasonal gatherings
  { id: "returned-umbrella-festival", title: "Returned Umbrella Festival", prompt: "Imagine a festival dedicated to umbrellas that somehow found their way home. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "borrowed-moons-parade", title: "Borrowed Moons Parade", prompt: "Imagine a parade where neighborhoods show off borrowed moons. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "forgotten-ideas-lantern-night", title: "Forgotten Ideas Lantern Night", prompt: "Imagine a lantern night for ideas people abandoned too early. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "ghost-neighborhood-summit", title: "Ghost Neighborhood Summit", prompt: "Imagine an annual summit where neighborhood ghosts compare haunting standards. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "impossible-seed-market", title: "Impossible Seed Market", prompt: "Imagine a market day devoted to buying and bartering impossible seeds. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "first-tea-after-disaster-celebration", title: "First Tea After Disaster Celebration", prompt: "Imagine a celebration of the first calm cup of tea after everything nearly went wrong. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "comet-potluck", title: "Comet Potluck", prompt: "Imagine a potluck organized around the sighting of a bright comet. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "monster-solstice-talent-show", title: "Monster Solstice Talent Show", prompt: "Imagine a winter-solstice talent show for monsters with surprisingly strong stage presence. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "haunted-house-spring-cleaning", title: "Haunted House Spring Cleaning", prompt: "Imagine a spring-cleaning day for haunted houses and their offended residents. Describe the signature event and ask what role the group would want during the celebration." },
  { id: "midnight-rehearsal-new-year", title: "Midnight Rehearsal New Year", prompt: "Imagine a second New Year celebration for everyone who missed the real midnight. Describe the signature event and ask what role the group would want during the celebration." },
];

export function pickBotModeIdleTopic(
  topics: ReadonlyArray<BotModeIdleTopic>,
  lastTopicId?: string,
  randomNumber = Math.random(),
): BotModeIdleTopic {
  if (topics.length === 0) {
    throw new Error("Bot mode idle topic bank cannot be empty.");
  }

  const candidates =
    topics.length > 1 && lastTopicId
      ? topics.filter((topic) => topic.id !== lastTopicId)
      : [...topics];
  const normalizedRandom = Number.isFinite(randomNumber)
    ? Math.min(Math.max(randomNumber, 0), 0.999_999_999_999)
    : 0;
  const index = Math.floor(normalizedRandom * candidates.length);
  return candidates[index] ?? candidates[candidates.length - 1] ?? topics[0]!;
}
