export const PRIVATECLAW_QR_ERROR_CORRECTION_LEVEL = "M" as const;
export const PRIVATECLAW_QR_IMAGE_MARGIN = 1;
export const PRIVATECLAW_QR_PNG_WIDTH = 320;
export const PRIVATECLAW_QR_SVG_MARGIN = 0;
export const PRIVATECLAW_QR_TERMINAL_MARGIN = 0;
